apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secret
    namespace: monitoring
type: Opaque
stringData:
    grafana-admin-user: ENC[AES256_GCM,data:MnKhRw==,iv:BtNR8G4rbEojOvL5zUNfwZH4YoTjkxpOV0OFwdlAcRc=,tag:w/hsus0X7sKwtm+NjFpj9g==,type:str]
    grafana-admin-password: ENC[AES256_GCM,data:lJc9WBJMRM7qkRWcwozOZA==,iv:2RudftiOKJ2dU8HgR2YJnAKPA9AMbUVCMhFPjWtMiFY=,tag:H12Tx4+b9fr9k84RHYvQJg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBrRkcz
            WDQxdVRvaENlWDFRU3ExQVlmREpOTEdvWUhqU0lQd0h1anRicmhNCmhaRWY3WW9S
            N1pIMTI0RWZKK0dVZEd1UTFmWGZQbStHMG9SZ09ZYkt1MGsKLS0tICtUaUJBVnFG
            WlJLVmdFWjZQMXcxWFNXUG9KbXlIUTJhbUhWcHRWL0Fwb1kKsFbc+Fy6rVyOtgXv
            GIKViSY938uy9YtFcSvItml604I53U8bcfuXy0VY26i4Ey24cb4kvRsjzhPz5NeT
            A/dEvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTC84OXRqMzg5d1Z2U3c4
            bHVKV1ZIb1BEdVZLQXhrN2NvZXUvU3dmZ1RBCnNpa3c5NzFET2hNYUZzSnIwYmlw
            Wms5bE1FeW8rcGFxUUNuQ1pnM2xaODQKLS0tIGpnbHJ3UmZVTFdRL1B5cE42TzFX
            b0ZMd0l5VjRtZ1F6dVFUREppZlg1dVEK7a8WoZzbvt84HkqevLnyNzfPDV0qIFaM
            9a3DdWtPSU6laxXNDmzIcBiVzy9WjddaKT3y58felPpdSVLigFWF0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGNNNzJpMmR5R2RjZ3VK
            NjJBekp1MUUza3hGRTl4cGVhL2NxTjgwUkRjCkcvdXI3bTJXbFg0aS9iaGQrYnNu
            OFYwdEl6TWFJQzBEVjh1U1VFMUFZSW8KLS0tIGxrUDNxTXdiNit6bndMckVUN3JF
            NWtlbWxEcFh0MlQ5Y2thd0FGU2UyVWsKPGwt7/dzZj3PmiMb8mRK41QhGKF2c3c+
            CaWm+GNXLrIQufK9GTE/H87RJVjdNdq5sChCOzMzQ6pwcS73PYEjDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T17:01:51Z"
    mac: ENC[AES256_GCM,data:wDkDOS/sYKYbaV6DXSyLmPDEAXIG3DlsBeFBbwFQpcPo5TrFcimy9b48c0YArBz7p0PPhRQeF1zlMsw5F1qvC3lbsQ7UKNmTdAxbo+QpVZMki90smvPPHOJ7P4WkDa/PrLV//O0hYplkUIFX01owbjWT9/NIB9KUhlb15gzjcck=,iv:977Y92e+Vr4k4qJvNReUAC/JnnWdg1CHGsZ9yoD1UQw=,tag:EHfS1uk0rE5F0ZVGfRFmbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
