apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gonic
  namespace: redmanager
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - gonic.home.parents-basement.win
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: gonic
          port: 4747
