apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redmanager
resources:
  - jellyfin-deployment.yaml
  - jellyfin-http-route.yaml
  - jellyfin-svc.yaml
  - namespace.yaml
  - postgres-deployment.yaml
  - postgres-svc.yaml
  - pvc.yaml
  - redmanager-deployment.yaml
  - redmanager-http-route.yaml
  - redmanager-svc.yaml
  - transmission-deployment.yaml
  - transmission-http-route.yaml
  - transmission-svc.yaml
