apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redmanager
resources:
  - gonic-deployment.yaml
  - gonic-http-route.yaml
  - gonic-svc.yaml
  - namespace.yaml
  - postgres-deployment.yaml
  - postgres-svc.yaml
  - pvc.yaml
  - redmanager-deployment.yaml
  - redmanager-http-route.yaml
  - redmanager-svc.yaml
  - transmission-configmap.yaml
  - transmission-deployment.yaml
  - transmission-http-route.yaml
  - transmission-svc.yaml
  - wrtag-deployment.yaml
  - wrtag-svc.yaml
