apiVersion: apps/v1
kind: Deployment
metadata:
  name: navidrome
  namespace: redmanager
  labels:
    app: navidrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: navidrome
  template:
    metadata:
      labels:
        app: navidrome
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: navidrome
          image: docker.io/deluan/navidrome:latest@sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
          env:
            - name: ND_MUSICFOLDER
              value: /music
            - name: ND_DATAFOLDER
              value: /data
            - name: ND_CACHEFOLDER
              value: /tmp-cache
            - name: ND_ENABLEFAVOURITES
              value: "false"
            - name: ND_ENABLESTARRATING
              value: "false"
            - name: ND_ENABLEINSIGHTSCOLLECTOR
              value: "false"
            - name: ND_CONFIGFILE
              value: "/data/navidrome.toml"
            - name: ND_DEVAUTOCREATEADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: ND_DEVAUTOCREATEADMINPASSWORD
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 4533
              name: http
              protocol: TCP
          volumeMounts:
            - name: music
              mountPath: /music
            - name: data
              mountPath: /data
            - name: tmp-cache
              mountPath: /tmp-cache

      volumes:
        - name: music
          persistentVolumeClaim:
            claimName: music
        - name: data
          persistentVolumeClaim:
            claimName: navidrome-data
        - name: tmp-cache
          emptyDir: {}
