apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redmanager
  namespace: redmanager
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - redmanager.home.parents-basement.win
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: redmanager
          port: 8080
