apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmanager
  namespace: redmanager
  labels:
    app: redmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmanager
  template:
    metadata:
      labels:
        app: redmanager
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: redmanager
          image: registry.gitlab.com/starfruit6000/redmanager:latest@sha256:5c1a8f191f7dce337caba3a81a819859fa77e71d69f06175c016f474cd2951fa
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "redmanager_db"
            - name: TRANSMISSION_HOST
              value: "transmission:9091"
            - name: TRANSMISSION_USER
              value: "admin"
            - name: TRANSMISSION_PASS
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: TRANSMISSION_PASS
            - name: REDMANAGER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: REDMANAGER_API_KEY
            - name: RED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: RED_API_KEY
            - name: WRTAG_WEB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: WRTAG_WEB_API_KEY
            - name: WRTAG_URL
              value: "http://wrtag:7373"
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
