apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: gluetun
          image: qmcgaw/gluetun@sha256:53c63cf35260ddd58da322ce1e1d87cb14358bbb011fba100676692be97be970
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: FIREWALL_INPUT_PORTS
              value: "9091"
            - name: SERVER_COUNTRIES
              value: Poland
            - name: PORT_FORWARD_ONLY
              value: on
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_PORT_FORWARDING
              value: on
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: WIREGUARD_PRIVATE_KEY
          ports:
            - containerPort: 9091
              protocol: TCP

        - name: transmission
          image: ghcr.io/home-operations/transmission:rolling@sha256:9809bf792c95d2258827509fe1fafabf74f86bd2469fcf4f0aba95f18283d1c7
          env:
            - name: TRANSMISSION__RPC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: TRANSMISSION_USER
            - name: TRANSMISSION__RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redmanager-secret
                  key: TRANSMISSION_PASS
          volumeMounts:
            - name: redmanager-download
              mountPath: /downloads
            - name: transmission-config
              mountPath: /config
      volumes:
        - name: redmanager-download
          persistentVolumeClaim:
            claimName: redmanager-download
        - name: transmission-config
          persistentVolumeClaim:
            claimName: transmission-config
