apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transmission
  namespace: redmanager
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
  hostnames:
    - transmission-redmanager.home.parents-basement.win
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: transmission
          port: 9091
