fearless:
  hosts:
    fearless-local.home.parents-basement.win:
      primary_interface: enp1s0
      root_password_hash: "{{ vault_proxmox_root_password_hash }}"
      clevis_bindings:
        device: /dev/vda3
        servers:
          - http://192.168.122.1:7500
