apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:G2iS0jzRU5NPfxFuNFE7a+v2jCaOelhePZ0QprTfaY/k1PLQOOu8pg==,iv:Z8l7D1iHjpMk5qUHzdtrJMMNdHpV9nQ+myY4RPWarlw=,tag:YmL1FjcWeUL8a7iJ06Gfrg==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBRcno1
            aS9tREtxWG5aSnJSai93V3ZpWkVXZ0ZIUXNRMkE2QlJMS2VyYXlvCkpVQmxtQmw3
            czdYZVkwQ3dQNXRVdWZEUG5SY0NPNmpPVzVNUDRHK2wxVVkKLS0tIGM4NFdacGhB
            R1RsVk9xa0pNT2N2Zjg5aFpCRkowbHVlMFFGSmpRSTNlZlEKS//Med6M/CsfVxxB
            6LqOXiJ0JzcPoKNCkQSqQFjCwMx21xd7GTSImb0IweCulvHYid4J4yVYjVJcPVdD
            Bs1bAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bHVHM2Z4YXNLOXdPOEVB
            Nkd4Y3Z4SGRQWnY1WEpGVzhjTzg1SlFrcW1jCndhSk9ZVWIxMzU5YXZMR1EzQ2Fu
            c3d2TmJtL25yV3kxc1FrbEVBNzRoOXcKLS0tIHBOYUwvUWR6aDhlRnErM2Q4YmxM
            ZHpTdzJCUm0rOEd3elZDdklkbGY2azQKbkjKQiSJqq3q5oA2gLYkc62JSCe4PnKr
            30GmfQVBlZfifTF/ThiPgQgjXK6AwTuoX2RXwaZQhkjYcoLe4cIAAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cEpzaEUxOFJBUkFZMHlq
            WFh1M0ZPL2tCR1BzT3pObHFCbnpXTkl5bjE0CkEycnNsWWFXUlFMY01UVzJjY2c0
            U1hWTTNxRTFCZWRpamxDMG1LMnYrWlEKLS0tIGZzcDFTZDNwb3BMMnRkb2FQaWNC
            VXhvVWlnWEtjNm5xUEZ3a0xiNVVwcjgKW6EpQXbmQC9ZnvdWzTV6T6NwUaoflQ4p
            6CsusJJR9H2gmgQ0Z4+GAE+WVrY73pW44bVOPhA/TCpWVSi/xmAr0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T21:08:08Z"
    mac: ENC[AES256_GCM,data:fe1zJ9ktkkDo2N7uZCdSBEZ4Zo1O3yzDwGbioBCPnDJbbU4Jp8JtXRWtV098TiMr7g/q1PnA45SYtXt2su9NqqgSelUS9tdA5jopwvn5S/fGO+9wwRCThQ1CUTOHcZOahB0LZUWmM3Tfh/f6peEI0rD+sbR2enm04dgpr+E34iw=,iv:t9KdSHJBl093Ic4NpG5uQjjycc+5/Bjm9E7mbv3AMQk=,tag:J0lc50AIHyNBJAdFqXUg5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
