apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-secret.enc.yaml
  - ../../base/configs/cert-manager
  - ../../base/configs/gateway
  - ../../base/configs/openebs
  - grafana-secret.enc.yaml
  - ../../base/configs/monitoring
patches:
  - path: lets-encrypt.yaml
