---
roles:
  - name: geerlingguy.swap
    version: 1.2.0
  - name: linux-system-roles.certificate
    version: 1.4.1
  - name: linux-system-roles.journald
    version: 1.5.2
  - name: linux-system-roles.nbde_client
    version: 1.3.6

collections:
  - name: freeipa.ansible_freeipa
    version: 1.14.7
  - name: ansible.posix
    version: 2.1.0
  - name: community.proxmox
    version: 1.4.0
  - name: community.crypto
    version: 3.0.5
