---
roles:
  - name: linux-system-roles.certificate
    version: 1.4.4
  - name: linux-system-roles.journald
    version: 1.5.2
  - name: linux-system-roles.nbde_client
    version: 1.3.8

collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.proxmox
    version: 1.5.0
  - name: community.crypto
    version: 3.1.1
  - name: community.general
    version: 12.4.0
