apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs-monitoring
  namespace: flux-system
spec:
  chart:
    spec:
      chart: monitoring
      reconcileStrategy: ChartVersion
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: openebs-monitoring
  interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kube-prometheus-stack:
      install: false
