apiVersion: v1
kind: Secret
metadata:
    name: arr-secret
    namespace: arr
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:wen/uPelvlxpR8wJmQddgVXrehjOlEXihU8zJ9TqkBGeoSAcCUt+pWbgKE8=,iv:OrLQYIP1bUQqsBpv1ZOYH4q4FYXlle0rddcSX33pA7Y=,tag:hx32xE3qKDV+G8hODi5y1A==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:BJmMoT5yaGePrFY=,iv:ucQ9bLEWPHIuIVuiO+oM6OchncCM0xwKL3wcNbJzgKM=,tag:Cu+kYAZGdgQPKj/ValhEkw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:KK++15nd2rXM7eMDyAk8Tr1gbLarVVpKTzL3sceO+Ms=,iv:G3fJAzAf2qJqXTqcwEJBVFMxsdJN1nEGP88Twthqeig=,tag:vuz/GigT8d5SKCUP6LIq4Q==,type:str]
    QBITTORRENT_PASS_HASH: ENC[AES256_GCM,data:AAxLfpc1jWcOuLOtKBbjwxYB6D5FfV+vLzhYlpPz6Nsbj3/X7ENTgr8vueRE6TrcYznbufHLzD6L98jrWD5ByycsKYoUjqyDq8m+KtV/PjfVzgxUwQi0BIzLfpk5UUFf0D73myeFBNa07Ys794PGfvY=,iv:BF1YpX7pQTOKkDq7HeggoERtWuXUGsYKHci7i+2uIKo=,tag:PsaTy4yQPgr+E6SpVHlEJw==,type:str]
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:mTaghaPqXtINsxobh6BZJTz3UKtzgV8p6cbPbLcpYQ1ItN9PGKNtInuQXtnI+0v37jW4RsImBNr2hWHml14lMbKcSQU4bOVJltXo8yRF1u6KYi6zbVFY95pK3OWDoFsFdKE3uB5l7i6HfJqwnq3nxe82lYRStF8+7mP0U0bzG5g=,iv:29D6l6UqUqlhg+NmJd+Z6D/ApP1844dQkFJmW6+1inI=,tag:qrkK+wY/S9UkX1Ri8qU7Hg==,type:str]
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:vyJoopPuphM5MRR1Q4KUjc9a0o5TeLmmQnkgz9ByDUWrVGgkr+NOnum1aapwuxkAFxaNu9DELCJhHJwyZ4b1KdVHhA52nDHWCpSQrvcEmlM/yJ+bemxfAk7SDbb7TG086MwK41IaKr5OrLUGVMqdzIH5/wIOhncC9Qt51/vhG5s=,iv:73/pU46OtdloNkDwbItywts8E65xBzg0VO77WMcyvyw=,tag:Ez2Cy4dul7JLEtM9WfSkaQ==,type:str]
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:JWWQ3x4eT0e0gKYo8iIMfkVxs5I9oGXwApfDbiUm0hOgiem0iauHKwCReDaGqD3cez2I8hkjJpLBbzVS+gjPeyItlIZq5l6IipAf3ApVSKK8qHNr+/oOysgTQwrEimPpRozIpqvgXh6pw9z6qzByP1QI7qyW5W74MzuUVkkFDiU=,iv:RaITZ+m9i2Oza1zyKIoPkZlRynOd2TMO4SWWyWpP8Y4=,tag:vNZDigIZNDENcdDPZnE5gw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBDQ0Ni
            VzBvNnBtcDlsOStkZ2EzYVFnK2FTMUlweDhoVHYrd1RFMmdjYW5zCmEyREpKQWov
            TjRqL1JQbFo1TzMzTnFja28zMmw4S3BpSk5ZcVNISjVHR0UKLS0tIGEzQWFrUmdw
            elpJNXo0dnRzaGlqb3BmU1Zwc3hpVlF4SjlTZWFOWTFuR28KzVpll3N1IjYEFWT1
            2B5RMVPImZmZarfmIX0lO2Qle+nOaldFZ/3vxXULSERTla4PGsGIUQX5F/pX1gi3
            1NUANw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFAxN3Zxbm1jcmo3bWpS
            QXZDNHRjTitMQ3NEdm9SZlkxTU5LdjBZRUcwCnFUdDlzZXJmZ1I3VVRmWHphZHo2
            QU9Sd1dTWXhuTys2ZzNDNVk1bk8waWcKLS0tIER3ckNscXMvWFI3ZXptQ3BrRFY5
            OEVRNWRaODJVamU0MVBXdGp0N2VrakEKSsrGuBn+ltbfKOxCym2yqLQ+uIEWRDt0
            iyddqgCVkOj5kUerxBhU67c8N46Kf6EDuXphhL5G3LaD9jnCxaKFsg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdmhyQnlSMHQrY0lTWHBI
            eUdmQk1VL3pUUUkyV3lNOEdQTUZ6T0NnMGtrCmlzZmwvdWtwWEJKUnZGais0UXNU
            UWg2N01KUmZPeE5DODRNVW5EVGZzbk0KLS0tIHQvNFZJaXdUVnJ6NUZXSHp5ZWdT
            RzlZQkw1d1pCNzB5MzYvb1FCTUhJWU0KsdczzuTGAiRutF8M+AoHAmC57lD2fUTz
            h1w7byg5qLbnXYHQzu2J75+c4hvjh3mxkC4CMu6TJR67H7JGIDs+nA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T18:05:13Z"
    mac: ENC[AES256_GCM,data:jHcWucFHfZXjwbNH9O7ISfoJtMgBaetg/jz8leVmz6RhPxN/j92BC96YDmSfmxhHJk91SQzr+3LFv1JDUouScQGNbV0g5hCDKfMiOVgaTrHX3PNaiaugXyha0e8CPwtP+Elx4CMN7vI7+9NaDYNjZxhl9zqq/Ah7gOGnm5frCbI=,iv:Qtyv/mNmflcx8WBFmR3tfBhDEwiSiEXIiiqp2jctlho=,tag:on7QiNKy4K5rnn10KVC6ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
