apiVersion: v1
kind: Secret
metadata:
    name: redmanager-secret
    namespace: redmanager
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ggN2WosWKzqwhkSLA+kCPQXLWTIGfP6gSUyfrVCh+SCDMDRcWJnpqmZWeoA=,iv:yvAY6X/st4ToKHqFWbI6VqXqjbw21AozBUMp8xZmRWM=,tag:FssaOFKJb1QnLkr2y6lxFg==,type:str]
    TRANSMISSION_USER: ENC[AES256_GCM,data:2RWoipUjNXb7fA==,iv:jub1+iiUphEW/qEmP9N7DZDZZSjxCqGjmdiRj24vS4A=,tag:eYjt6LvYDirtVNphrW5kAg==,type:str]
    TRANSMISSION_PASS: ENC[AES256_GCM,data:HlDbn+Gf/Kxz8lOF3TgikA==,iv:jKbWa2HVyFJAXyVap5uHu7/0cDTHGdHzzCJNzkG4yCo=,tag:it/iVG/REWMx00hmlpjeZA==,type:str]
    REDMANAGER_API_KEY: ENC[AES256_GCM,data:KJKYMxsrogDi0GQhsRA1GA==,iv:puVwDfu7w+2zJtYKOCp5WJoS8n13w6xJjdrH7XBDjhQ=,tag:EGfkwbUSvuf6QX8Fs2DgiQ==,type:str]
    RED_API_KEY: ENC[AES256_GCM,data:9//Tz+3epS41C8NOzzXA30tzA+nw8Lis+7kU9h48DN7UDXfymsetdAw=,iv:pbueGMIdjzPe0fcMov9jZYFAXI2sEEedtKBb1vAvHRc=,tag:jPGffdR12Xi4MgScMuSllw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:s/j60W3PzUbzpAaYB1LCdw==,iv:IBid7WtpgkB5BeQ/I5uqN6uSDiLtq0anD/9LxQydqAs=,tag:bb6/MhvTBsd3R+b5jTGiew==,type:str]
    DB_USER: ENC[AES256_GCM,data:k4iI7oAYXncqUw==,iv:wDXBn/JgAtRytokDct7iKYa9Ajb2Olm8RP8s6I9LUAA=,tag:/LZCPtXIoJQo5be+vwrwkQ==,type:str]
    WRTAG_WEB_API_KEY: ENC[AES256_GCM,data:KMdp6vhOADX0Nk7JGduOLQ==,iv:9KtorYKV7/L48P/Art8dzZE0EO0meOIFtYXe1MmZu7U=,tag:/MxDwLTiGhQOXQWFHaUOPw==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPOqLcTHDmSWixB1H74ZayWiExXBPmEzfWC90I8Nh1Lb
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGNnVERGUSBrRkcz
            WDQxdVRvaENlWDFRU3ExQVlmREpOTEdvWUhqU0lQd0h1anRicmhNCmhaRWY3WW9S
            N1pIMTI0RWZKK0dVZEd1UTFmWGZQbStHMG9SZ09ZYkt1MGsKLS0tICtUaUJBVnFG
            WlJLVmdFWjZQMXcxWFNXUG9KbXlIUTJhbUhWcHRWL0Fwb1kKsFbc+Fy6rVyOtgXv
            GIKViSY938uy9YtFcSvItml604I53U8bcfuXy0VY26i4Ey24cb4kvRsjzhPz5NeT
            A/dEvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uvccut3fganrx0uztudlujeeenv3mhpa4y3pgd8dstagcqknnp3q5p4zhm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTC84OXRqMzg5d1Z2U3c4
            bHVKV1ZIb1BEdVZLQXhrN2NvZXUvU3dmZ1RBCnNpa3c5NzFET2hNYUZzSnIwYmlw
            Wms5bE1FeW8rcGFxUUNuQ1pnM2xaODQKLS0tIGpnbHJ3UmZVTFdRL1B5cE42TzFX
            b0ZMd0l5VjRtZ1F6dVFUREppZlg1dVEK7a8WoZzbvt84HkqevLnyNzfPDV0qIFaM
            9a3DdWtPSU6laxXNDmzIcBiVzy9WjddaKT3y58felPpdSVLigFWF0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zkersaavam0z9fq6a8p5xwkw504csvel7gw5csm49vvvfyk6x9ksw2t49m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WGNNNzJpMmR5R2RjZ3VK
            NjJBekp1MUUza3hGRTl4cGVhL2NxTjgwUkRjCkcvdXI3bTJXbFg0aS9iaGQrYnNu
            OFYwdEl6TWFJQzBEVjh1U1VFMUFZSW8KLS0tIGxrUDNxTXdiNit6bndMckVUN3JF
            NWtlbWxEcFh0MlQ5Y2thd0FGU2UyVWsKPGwt7/dzZj3PmiMb8mRK41QhGKF2c3c+
            CaWm+GNXLrIQufK9GTE/H87RJVjdNdq5sChCOzMzQ6pwcS73PYEjDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T01:49:37Z"
    mac: ENC[AES256_GCM,data:nLH2QhS1+pi7sQHLkdvmT6GdCK6YoAl3RAZ6JxrL7pIorPJu5o7UGNP+WmccNFTGX9pOVW8eeK4C7bKVBd2XZD1cflaEKSsspGEwYpCQofVzVBoHQW1z+pBcG7+JGsU/iIeS5+ZtyqgHWYEf0g6uam4/DucNWJibfT5Q+1eIL1A=,iv:SOM80ReyWIg+U/07vIwRh4kJL/cPKCv93bsO00kBjYM=,tag:HCXesVzcKr6KIdOQuGpTuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
