apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - https://github.com/prometheus-operator/prometheus-operator/bundle.yaml?ref=v0.71.2
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: not-important
      namespace: monitoring
    fieldSpecs:
      - path: metadata/namespace
        create: true
