apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfspv
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  fstype: "zfs"
  shared: "yes"
  poolname: "tank"
  compression: "lz4"
provisioner: zfs.csi.openebs.io
reclaimPolicy: Retain
