---
roles:
  - name: geerlingguy.swap
    version: 1.3.0
  - name: linux-system-roles.certificate
    version: 1.4.1
  - name: linux-system-roles.journald
    version: 1.5.0

collections:
  - name: freeipa.ansible_freeipa
    version: 1.14.7
