apiVersion: v1
kind: Service
metadata:
  name: arr
spec:
  type: ClusterIP
  selector:
    app: arr
  ports:
    - name: prowlarr
      port: 9696
    - name: sonarr
      port: 8989
    - name: radarr
      port: 7878
