apiVersion: v1
kind: ConfigMap
metadata:
  name: configarr
data:
  config.yml: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://arr:8989
        api_key: !env SONARR__AUTH__APIKEY
        quality_definition:
          type: series
        include:
          # WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          # WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p
        custom_formats: []
        download_clients:
          data:
            - name: "qBittorrent"
              type: qbittorrent
              enable: true
              priority: 1
              remove_completed_downloads: false
              remove_failed_downloads: true
              fields:
                host: qbittorrent
                port: 8080
                use_ssl: false
                url_base: /
                username: !env QBITTORRENT_USER
                password: !env QBITTORRENT_PASS
          update_password: true
        root_folders:
          - /data/media/tv

    radarr:
      movies:
        base_url: http://arr:7878
        api_key: !env RADARR__AUTH__APIKEY
        include:
          - template: radarr-quality-definition-movie
          - template: radarr-quality-profile-hd-bluray-web
          - template: radarr-custom-formats-hd-bluray-web
          - template: radarr-quality-profile-uhd-bluray-web
          - template: radarr-custom-formats-uhd-bluray-web
          - template: radarr-quality-profile-remux-web-1080p
          - template: radarr-custom-formats-remux-web-1080p
          - template: radarr-quality-profile-remux-web-2160p
          - template: radarr-custom-formats-remux-web-2160p
          - template: radarr-quality-profile-anime
          - template: radarr-custom-formats-anime
        custom_formats: []
        download_clients:
          data:
            - name: "qBittorrent"
              type: qbittorrent
              enable: true
              priority: 1
              remove_completed_downloads: false
              remove_failed_downloads: true
              fields:
                host: qbittorrent
                port: 8080
                use_ssl: false
                url_base: /
                username: !env QBITTORRENT_USER
                password: !env QBITTORRENT_PASS
          update_password: true
        root_folders:
          - /data/media/movies
