apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - arr-deployment.yaml
  - arr-svc.yaml
  - configarr-config.yaml
  - configarr-job.yaml
  - namespace.yaml
  - pvc.yaml
  - transmission-configmap.yaml
  - transmission-deployment.yaml
  - transmission-svc.yaml
