apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arr
resources:
  - arr-deployment.yaml
  - arr-svc.yaml
  - configarr-config.yaml
  - configarr-job.yaml
  - jellyfin-deployment.yaml
  - jellyfin-http-route.yaml
  - jellyfin-svc.yaml
  - namespace.yaml
  - pvc.yaml
  - qbittorrent-config.yaml
  - qbittorrent-deployment.yaml
  - qbittorrent-svc.yaml
