apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      #dnsPolicy: Default
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: gluetun-sidecar
          image: qmcgaw/gluetun@sha256:53c63cf35260ddd58da322ce1e1d87cb14358bbb011fba100676692be97be970
          restartPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: FIREWALL_INPUT_PORTS
              value: "8080"
            - name: SERVER_COUNTRIES
              value: Poland
            - name: PORT_FORWARD_ONLY
              value: on
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_PORT_FORWARDING
              value: on
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: WIREGUARD_PRIVATE_KEY
            - name: LOG_LEVEL
              value: info
            - name: BLOCK_MALICIOUS
              value: off
            - name: BLOCK_SURVEILLANCE
              value: off
            - name: BLOCK_ADS
              value: off
            - name: HEALTH_RESTART_VPN
              value: on
            - name: DNS_UPSTREAM_IPV6
              value: on
            - name: DNS_SERVER
              value: off
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "nslookup google.com"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "nslookup google.com"
            initialDelaySeconds: 600
            periodSeconds: 30
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: gomplate-qbittorrent-config
          image: hairyhenderson/gomplate:alpine@sha256:0b81da292a603e826c2be71484b17b08f67a6ee23519be45c7e27d8ed1db1e70
          env:
            - name: QBITTORRENT_PASS_HASH
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: QBITTORRENT_PASS_HASH
            - name: QBITTORRENT_USER
              valueFrom:
                secretKeyRef:
                  name: arr-secret
                  key: QBITTORRENT_USER
          command:
            - /bin/gomplate
            - -f
            - /tmp/qBittorrent.conf.tmpl
            - -o
            - /config/qBittorrent/qBittorrent.conf
          volumeMounts:
            - name: config-map-tmpl
              mountPath: /tmp/qBittorrent.conf.tmpl
              subPath: qBittorrent.conf.tmpl
            - name: qbittorrent-config
              mountPath: /config

      containers:
        - name: qbittorrent
          image: ghcr.io/home-operations/qbittorrent:rolling@sha256:56ecd30a7f5e1357daf5eea2a6935134d329b7b268a3a9b9c67041b65fb87fc6
          volumeMounts:
            - name: data
              mountPath: /data
            - name: qbittorrent-config
              mountPath: /config

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: config-map-tmpl
          configMap:
            name: qbittorrent-config-tmpl
